import mod.client.extraClientApi as clientApi
import mod.server.extraServerApi as serverApi

class LevelServer:
    compServer = serverApi.GetEngineCompFactory()
    levelId = serverApi.GetLevelId()

    game = compServer.CreateGame(levelId)
    chunkSource = compServer.CreateChunkSource(levelId)
    achievement = compServer.CreateAchievement(levelId)
    biome = compServer.CreateBiome(levelId)
    dimension = compServer.CreateDimension(levelId)
    blockInfo = compServer.CreateBlockInfo(levelId)
    weather = compServer.CreateWeather(levelId)
    time = compServer.CreateTime(levelId)
    block = compServer.CreateBlock(levelId)
    blockEntity = compServer.CreateBlockEntity(levelId)
    blockEntityData = compServer.CreateBlockEntityData(levelId)
    blockState = compServer.CreateBlockState(levelId)
    blockUseEventWhiteList = compServer.CreateBlockUseEventWhiteList(levelId)
    message = compServer.CreateMsg(levelId)
    command = compServer.CreateCommand(levelId)
    chestBlock = compServer.CreateChestBlock(levelId)
    explosion = compServer.CreateExplosion(levelId)
    extraData = compServer.CreateExtraData(levelId)
    feature = compServer.CreateFeature(levelId)
    itemBanned = compServer.CreateItemBanned(levelId)
    mobSpawn = compServer.CreateMobSpawn(levelId)
    projectile = compServer.CreateProjectile(levelId)
    portal = compServer.CreatePortal(levelId)
    recipe = compServer.CreateRecipe(levelId)
    redstone = compServer.CreateRedStone(levelId)

class LevelClient:
    compClient = clientApi.GetEngineCompFactory()
    levelId = clientApi.GetLevelId()
    localPlayerId = clientApi.GetLocalPlayerId()

    achievement = compClient.CreateAchievement(levelId)
    actorRender = compClient.CreateActorRender(levelId)
    biome = compClient.CreateBiome(levelId)
    block = compClient.CreateBlock(levelId)
    blockGeometry = compClient.CreateBlockGeometry(levelId)
    blockInfo = compClient.CreateBlockInfo(levelId)
    blockUseEventWhiteList = compClient.CreateBlockUseEventWhiteList(levelId)
    camera = compClient.CreateCamera(levelId)
    chunkSource = compClient.CreateChunkSource(levelId)
    configClient = compClient.CreateConfigClient(levelId)
    customAudio = compClient.CreateCustomAudio(levelId)
    dimension = compClient.CreateDimension(levelId)
    drawing = compClient.CreateDrawing(levelId)
    fog = compClient.CreateFog(levelId)
    game = compClient.CreateGame(levelId)
    model = compClient.CreateModel(levelId)
    neteaseShop = compClient.CreateNeteaseShop(levelId)
    operation = compClient.CreateOperation(levelId)
    playerView = compClient.CreatePlayerView(levelId)
    postProcess = compClient.CreatePostProcess(levelId)
    recipe = compClient.CreateRecipe(levelId)
    skyRender = compClient.CreateSkyRender(levelId)
    textBoard = compClient.CreateTextBoard(levelId)
    textNotify = compClient.CreateTextNotifyClient(levelId)
    virtualWorld = compClient.CreateVirtualWorld(levelId)