
NAMESPACE = "MODEXAMPLE"
"""命名空间"""
SYSTEM_NAME_SERVER = "SAMPLESERVER"
"""服务端系统名"""
SYSTEM_NAME_CLIENT = "SAMPLECLIENT"
"""客户端系统名"""
ENTRY_PATH_SERVER = "example_use_file"
"""服务端入口文件"""
ENTRY_PATH_CLIENT = "example_client"
"""客户端入口文件"""